  language: node_js
  node_js:
    - "v11.5.0"
  cache:
    directories:
      - "node_modules"
  install:
      - npm install -g typescript codecov
      - npm install
      - npm test && npm run upload-coverage
